version: '3.8'

services:
  keycloak_postgres:
    image: postgres:16 # as per 06/2025
    container_name: auth_keycloak_postgres
    hostname: auth_keycloak_postgres
    restart: unless-stopped
    ports:
      - 6432:6432
    volumes:
      - ./volume/data:${PGDATA}
    environment:
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4 # as per 06/2025
    container_name: auth_keycloak
    hostname: auth_keycloak
    restart: unless-stopped
    ports:
      - 6080:6080
    volumes:
      - ./volume/import:/opt/keycloak/data/import
      - ./volume/providers:/opt/keycloak/providers
      - ./volume/themes/disbun:/opt/keycloak/themes/disbun
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_PORT: ${KC_DB_URL_PORT}
      KC_DB_DATABASE: ${KC_DB_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED}
      KEYCLOAK_HTTP_ENABLED: ${KC_HTTP_ENABLED}
      KEYCLOAK_HTTPS_PORT: 0
      KEYCLOAK_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}
      KC_PROXY: ${KC_PROXY}
      KC_SSL_REQUIRED: ${KC_SSL_REQUIRED}
      # KC_HTTP_RELATIVE_PATH: /keycloak
    env_file:
      - .env
    depends_on:
      - keycloak_postgres

networks:
  gateway-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  keycloak_data:
    driver: local
