volumes:
  chain-orderer.jabarchain.me:
  chain-orderer2.jabarchain.me:
  chain-orderer3.jabarchain.me:
  pusat.chain-bpsbp.jabarchain.me:
  cert.chain-bpsbp.jabarchain.me:
  sekretariat.chain-disbun.jabarchain.me:
  digital.chain-disbun.jabarchain.me:


networks:
  fabric_benih:
    name: fabric_benih
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1450"
services:
  # Certificate Authority Services
  ca_bpsbp:
    image: hyperledger/fabric-ca:1.5.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bpsbp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/bpsbp:/etc/hyperledger/fabric-ca-server
    container_name: ca_bpsbp
    networks:
      - fabric_benih

  ca_disbun:
    image: hyperledger/fabric-ca:1.5.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-disbun
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/disbun:/etc/hyperledger/fabric-ca-server
    container_name: ca_disbun
    networks:
      - fabric_benih

  ca_orderer:
    image: hyperledger/fabric-ca:1.5.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - fabric_benih

  # Orderer Service
  chain-orderer.jabarchain.me:
    container_name: chain-orderer.jabarchain.me
    image: hyperledger/fabric-orderer:2.4.7
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=chain-orderer.jabarchain.me:9443
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./organizations/ordererOrganizations/jabarchain.me/orderers/chain-orderer.jabarchain.me/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/jabarchain.me/orderers/chain-orderer.jabarchain.me/tls/:/var/hyperledger/orderer/tls
      - chain-orderer.jabarchain.me:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - fabric_benih

  # Orderer Service 2
  chain-orderer2.jabarchain.me:
    container_name: chain-orderer2.jabarchain.me
    image: hyperledger/fabric-orderer:2.4.7
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=chain-orderer2.jabarchain.me:8443
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8053
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./organizations/ordererOrganizations/jabarchain.me/orderers/chain-orderer2.jabarchain.me/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/jabarchain.me/orderers/chain-orderer2.jabarchain.me/tls/:/var/hyperledger/orderer/tls
      - chain-orderer2.jabarchain.me:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
      - 8053:8053
      - 8443:8443
    networks:
      - fabric_benih

  # Orderer Service 3
  chain-orderer3.jabarchain.me:
    container_name: chain-orderer3.jabarchain.me
    image: hyperledger/fabric-orderer:2.4.7
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=chain-orderer3.jabarchain.me:10443
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9053
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./organizations/ordererOrganizations/jabarchain.me/orderers/chain-orderer3.jabarchain.me/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/jabarchain.me/orderers/chain-orderer3.jabarchain.me/tls/:/var/hyperledger/orderer/tls
      - chain-orderer3.jabarchain.me:/var/hyperledger/production/orderer
    ports:
      - 9050:9050
      - 9053:9053
      - 10443:10443
    networks:
      - fabric_benih

  # BPSBP Peer0 (Pusat)
  pusat.chain-bpsbp.jabarchain.me:
    container_name: pusat.chain-bpsbp.jabarchain.me
    image: hyperledger/fabric-peer:2.4.7
    privileged: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_benih
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=pusat.chain-bpsbp.jabarchain.me
      - CORE_PEER_ADDRESS=pusat.chain-bpsbp.jabarchain.me:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=pusat.chain-bpsbp.jabarchain.me:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=pusat.chain-bpsbp.jabarchain.me:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pusat.chain-bpsbp.jabarchain.me:7051
      - CORE_PEER_LOCALMSPID=BPSBPBenihMSP
      - CORE_OPERATIONS_LISTENADDRESS=pusat.chain-bpsbp.jabarchain.me:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock:z
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ./builders:/opt/gopath/src/github.com/hyperledger/fabric/peer/external_builder
      - ./organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/pusat.chain-bpsbp.jabarchain.me/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/pusat.chain-bpsbp.jabarchain.me/tls:/etc/hyperledger/fabric/tls
      - pusat.chain-bpsbp.jabarchain.me:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - fabric_benih

  # BPSBP Peer1 (Cert)
  cert.chain-bpsbp.jabarchain.me:
    container_name: cert.chain-bpsbp.jabarchain.me
    image: hyperledger/fabric-peer:2.4.7
    privileged: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_benih
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=cert.chain-bpsbp.jabarchain.me
      - CORE_PEER_ADDRESS=cert.chain-bpsbp.jabarchain.me:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=cert.chain-bpsbp.jabarchain.me:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=pusat.chain-bpsbp.jabarchain.me:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=cert.chain-bpsbp.jabarchain.me:8051
      - CORE_PEER_LOCALMSPID=BPSBPBenihMSP
      - CORE_OPERATIONS_LISTENADDRESS=cert.chain-bpsbp.jabarchain.me:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock:z
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ./builders:/opt/gopath/src/github.com/hyperledger/fabric/peer/external_builder
      - ./organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/cert.chain-bpsbp.jabarchain.me/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/cert.chain-bpsbp.jabarchain.me/tls:/etc/hyperledger/fabric/tls
      - cert.chain-bpsbp.jabarchain.me:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
      - 9445:9445
    networks:
      - fabric_benih

  # Disbun Peer0 (Sekretariat)
  sekretariat.chain-disbun.jabarchain.me:
    container_name: sekretariat.chain-disbun.jabarchain.me
    image: hyperledger/fabric-peer:2.4.7
    privileged: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_benih
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=sekretariat.chain-disbun.jabarchain.me
      - CORE_PEER_ADDRESS=sekretariat.chain-disbun.jabarchain.me:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=sekretariat.chain-disbun.jabarchain.me:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=sekretariat.chain-disbun.jabarchain.me:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=sekretariat.chain-disbun.jabarchain.me:9051
      - CORE_PEER_LOCALMSPID=DisbunBenihMSP
      - CORE_OPERATIONS_LISTENADDRESS=sekretariat.chain-disbun.jabarchain.me:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock:z
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ./builders:/opt/gopath/src/github.com/hyperledger/fabric/peer/external_builder
      - ./organizations/peerOrganizations/chain-disbun.jabarchain.me/peers/sekretariat.chain-disbun.jabarchain.me/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/chain-disbun.jabarchain.me/peers/sekretariat.chain-disbun.jabarchain.me/tls:/etc/hyperledger/fabric/tls
      - sekretariat.chain-disbun.jabarchain.me:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 9446:9446
    networks:
      - fabric_benih

  # Disbun Peer1 (Digital)
  digital.chain-disbun.jabarchain.me:
    container_name: digital.chain-disbun.jabarchain.me
    image: hyperledger/fabric-peer:2.4.7
    privileged: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_benih
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=digital.chain-disbun.jabarchain.me
      - CORE_PEER_ADDRESS=digital.chain-disbun.jabarchain.me:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=digital.chain-disbun.jabarchain.me:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=sekretariat.chain-disbun.jabarchain.me:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=digital.chain-disbun.jabarchain.me:10051
      - CORE_PEER_LOCALMSPID=DisbunBenihMSP
      - CORE_OPERATIONS_LISTENADDRESS=digital.chain-disbun.jabarchain.me:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock:z
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ./builders:/opt/gopath/src/github.com/hyperledger/fabric/peer/external_builder
      - ./organizations/peerOrganizations/chain-disbun.jabarchain.me/peers/digital.chain-disbun.jabarchain.me/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/chain-disbun.jabarchain.me/peers/digital.chain-disbun.jabarchain.me/tls:/etc/hyperledger/fabric/tls
      - digital.chain-disbun.jabarchain.me:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 10051:10051
      - 9447:9447
    networks:
      - fabric_benih

  # CLI Tools Container
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4.7
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=pusat.chain-bpsbp.jabarchain.me:7051
      - CORE_PEER_LOCALMSPID=BPSBPBenihMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/pusat.chain-bpsbp.jabarchain.me/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/pusat.chain-bpsbp.jabarchain.me/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/peers/pusat.chain-bpsbp.jabarchain.me/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/Admin@chain-bpsbp.jabarchain.me/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock:z
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - chain-orderer.jabarchain.me
      - chain-orderer2.jabarchain.me
      - chain-orderer3.jabarchain.me
      - pusat.chain-bpsbp.jabarchain.me
      - cert.chain-bpsbp.jabarchain.me
      - sekretariat.chain-disbun.jabarchain.me
      - digital.chain-disbun.jabarchain.me
    networks:
      - fabric_benih
