name: Benih Certification Network
version: "2.0.0"
caliper:
  blockchain: fabric

channels:
  - channelName: benihchannel
    contracts:
      - id: benih-certification

organizations:
  - mspid: BPSBPBenihMSP
    identities:
      certificates:
        - name: appUser
          clientSignedCert:
            path: /Users/rangga/playground/tesis_bismillah/blockchain/caliper/../network/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/appUser@chain-bpsbp.jabarchain.me/msp/signcerts/cert.pem
          clientPrivateKey:
            path: /Users/rangga/playground/tesis_bismillah/blockchain/caliper/../network/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/appUser@chain-bpsbp.jabarchain.me/msp/keystore/8480dba3989547ab5e0e1de21e81d74d12fc5f7fdc63e755977ef1cc666d7b16_sk
    connectionProfile:
      path: ./networks/connection-remote.yaml
      discover: true

