name: Benih Certification Network
version: "2.0.0"
caliper:
  blockchain: fabric

channels:
  - channelName: benihchannel
    contracts:
      - id: benih-certification

organizations:
  - mspid: BPSBPBenihMSP
    identities:
      certificates:
        - name: appUser
          clientSignedCert:
            path: /Users/rangga/playground/tesis_bismillah/blockchain/caliper/../network/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/appUser@chain-bpsbp.jabarchain.me/msp/signcerts/cert.pem
          clientPrivateKey:
            path: /Users/rangga/playground/tesis_bismillah/blockchain/caliper/../network/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/appUser@chain-bpsbp.jabarchain.me/msp/keystore/c3629372780a0289af7f2967bc3b99789b5c2e61872ffc3c5715a3f171e67989_sk
    connectionProfile:
      path: ./networks/connection-bpsbp.yaml
      discover: true

