name: Benih Certification Network Remote
version: "2.0.0"
caliper:
  blockchain: fabric

channels:
  - channelName: benihchannel
    contracts:
      - id: benih-certification

organizations:
  - mspid: BPSBPBenihMSP
    identities:
      certificates:
        - name: appUser
          clientSignedCert:
            path: /Users/rangga/playground/tesis_bismillah/blockchain/caliper/../network/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/appUser@chain-bpsbp.jabarchain.me/msp/signcerts/cert.pem
          clientPrivateKey:
            path: /Users/rangga/playground/tesis_bismillah/blockchain/caliper/../network/organizations/peerOrganizations/chain-bpsbp.jabarchain.me/users/appUser@chain-bpsbp.jabarchain.me/msp/keystore/6b9a7144a8ef87a0760d57be5487b319a9f764d5ab47d73b188ca790cb4b7e64_sk
    connectionProfile:
      path: ./networks/connection-remote.yaml
      discover: true

