networks:
  fabric_benih:
    name: fabric_benih
    driver: bridge

services:
  # Chaincode-as-a-Service Container
  seedbatch.ccaas:
    container_name: seedbatch.ccaas
    image: seedbatch-ccaas:latest
    environment:
      - CHAINCODE_ID=seedbatch:1.0
      - CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - 9999:9999
    networks:
      - fabric_benih
